// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-kwgsh0Ik9GTDNjeErz32SF6kQ8jnM9A',
    appId: '1:969937027458:web:1e75b237c8942735a4cf9b',
    messagingSenderId: '969937027458',
    projectId: 'flashcard-e7778',
    authDomain: 'flashcard-e7778.firebaseapp.com',
    storageBucket: 'flashcard-e7778.firebasestorage.app',
    measurementId: 'G-SC9YVF5433',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz6tyZVkvUnjvqm48HLpTjXSs20sbusD0',
    appId: '1:969937027458:android:1e535e11f784ab7aa4cf9b',
    messagingSenderId: '969937027458',
    projectId: 'flashcard-e7778',
    storageBucket: 'flashcard-e7778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwbALVlTWgxtN7PNprbHZ32wdQtHrzsEI',
    appId: '1:969937027458:ios:947d117d3ad8124fa4cf9b',
    messagingSenderId: '969937027458',
    projectId: 'flashcard-e7778',
    storageBucket: 'flashcard-e7778.firebasestorage.app',
    iosBundleId: 'com.example.flashcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwbALVlTWgxtN7PNprbHZ32wdQtHrzsEI',
    appId: '1:969937027458:ios:947d117d3ad8124fa4cf9b',
    messagingSenderId: '969937027458',
    projectId: 'flashcard-e7778',
    storageBucket: 'flashcard-e7778.firebasestorage.app',
    iosBundleId: 'com.example.flashcard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-kwgsh0Ik9GTDNjeErz32SF6kQ8jnM9A',
    appId: '1:969937027458:web:cdfe2e2049041e22a4cf9b',
    messagingSenderId: '969937027458',
    projectId: 'flashcard-e7778',
    authDomain: 'flashcard-e7778.firebaseapp.com',
    storageBucket: 'flashcard-e7778.firebasestorage.app',
    measurementId: 'G-L08MFYNW1D',
  );
}
